### ISSUE TITLE
namespace handling

### ISSUE THREAD

**Issue by skandragon** [wingyu/rbattlenet#14]
I'm still new to the WoW APIs, but I understand some calls require namespaces, and some URIs can be identical other than the namespace.  While this feels like a rather badly written API where it's specifically not used for versioning...  there it is.

For instance, this call is easy to handle (which I will make a PR for later):

```
module RBattlenet
  module Wow
    class Battlepet
      def self.find_all
        uri = RBattlenet.base_uri("data/wow/pet/index")
        pp uri
        RBattlenet.get(uri, "namespace=static-#{RBattlenet.region}")
      end
    end
  end
end
```

This call returns a list of all pets, perhaps not in a super useful format.  It requires that specific namespace, so this call is likely easy to hard code.  What about those that do not?  Is there an overall plan on handling this?

**Comment by wingyu** [comment]
Hey @skandragon, I haven't looked into the WoW APIs in a long time and unfortunately I don't really have time atm to get back into it,  thus there are no plans to address this :(

However, PRs are most welcome and appreciated 🙇 

Sorry I can't be of more help at this point in time!

**Comment by skandragon** [comment]
Good enough :) . It just means whatever I do, if I also find the time...  won't conflict with your plans.  Thanks!
