### ISSUE TITLE
(Request) PvP Stats and Rank

### ISSUE THREAD

**Issue by sgtevmckay** [wingyu/rbattlenet#6]
Got a request from a PvP Guild using Discord.
Is there a way to return PvP Stas?
ie. Season Ranking, number of fights won/lost 
something about information regarding "rbgs, 3s, 2s, 5s etc"

I do not PvP, so I am not much help here :/
So I am unaware of what information a PvP'er would be seeking beyond Rank

Apparently folks are loving this.

Thanks for your hard work <3

**Comment by wingyu** [comment]
Hey @sgtevmckay,

You can access PVP data for a specific character with something like this:

```
character = RBattlenet::Wow::Character.find(
  name: "milhause",
  realm: "saurfang",
  fields: ["pvp"]
)

p character['pvp']
```

With that, you can view a character's seasons played/won/lost regarding 2v2s, 3v3s, 5v5s and RBGs

You can view PVP rankings via something like `RBattlenet::Wow::Pvp.find_bracket(bracket: "2v2")`

Let me know if theres anything more I can help out with!

**Comment by sgtevmckay** [comment]
Thank you so much :D
