### ISSUE TITLE
Adjusted the new API URI

### ISSUE THREAD

**Issue by hageneez** [wingyu/rbattlenet#7]
in rbattlenet.rb (line 71-73)
    def base_uri(path)
      "https://#{@@region}.battle.net/api/#{path}"
    end

Keep running into connection errors, is there any way i can track what kinda connection error im getting?

Any help would be greatly appreciated.

**Comment by wingyu** [comment]
Hey @hageneez

You might be getting errors as the uri may not exist? Have a look at https://dev.battle.net/io-docs and play with the API there, The Request URI section will have the exact base URI you need

What exactly are you using it for and why are you changing `base_uri` method? the Base uri (at least for WoW) has not changed and is still `<region>.api.battle.net` I think.

Either way, it'd be easier to debug by running the tests, where you could print out the exact uri you are hitting

**Comment by hageneez** [comment]
Ok thank you for the respond,  i think i misread some info about base_uri. (my mistake).

I think i found the issue, getting a SSL cert error on the API request.

 SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)

Guess i gotta figure this one out somehow.
